### ISSUE TITLE
MIME type error with jsonp ajax call

### ISSUE THREAD

**Issue by orbitka** [annalexc/feeltrip#40]
I have an issue with the ajax call to jsonp format. I am getting an error:

![image](https://cloud.githubusercontent.com/assets/13858896/15225583/012085f2-184d-11e6-80bb-62c6885ffc48.png)

Refused to execute script from 'http://api.timezonedb.com/?callback=jQuery2130036427453814006805_1463077229493&_=1463077229494' because its MIME type ('application/xml') is not executable, and strict MIME type checking is enabled.

The script which I am trying to execute is below. Can you help me to solve this puzzle?
# 

  var $timezonedbKey = 'IQATFHPIVIXW';

  function getTime(latitude, longitude) {

```
var requestTime = $.ajax({
url:'http://api.timezonedb.com',
type: "GET",
dataType: "jsonp",
key: $timezonedbKey,
lat: $latitude,
lng: $longitude,
success: function(res){
  console.log('lat = ' + lat + '/ lng = ' + lng);
  console.log('res = ' + res);
  console.log(url);
}
```

  })

**Comment by DZGoldman** [comment]
I may be of assistance — where ya at?

**Comment by DZGoldman** [comment]
See these:

http://stackoverflow.com/questions/24528211/refused-to-execute-script-from-because-its-mime-type-application-json-is

http://stackoverflow.com/questions/15899357/node-js-res-setheadercontent-type-text-javascript-pushing-the-response-j
